config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'rooms#index'
  
  resources :rooms,  only: [:index, :new, :create, :show] do
    resources :answers, only: [:index, :new, :create]
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
    belongs_to :user
    belongs_to :room

    # validates :ans, presence: true
    # validates :point, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/room.rb
class Room < ApplicationRecord
    belongs_to :user
    has_many :answers

    validates :target, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :rooms
         has_many :answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

    def index
    end


    def create
        @answer = Answer.new(ans_params)
        @answer.save
        @room = Room.find(params[:room_id])
        
        redirect_to room_path(@room.id)
    end


    private

    def ans_params
        params.require(:answer).permit(:ans,:point,:room_id,:user_id).merge(user_id: current_user.id, room_id: params[:room_id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :birth])
    end

    def basic_auth
      authenticate_or_request_with_http_basic do |username, password|
        username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
      end
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
    before_action :authenticate_user!
    before_action :room_all,  only: [:index, :new, :show]

    def index
    end

    def new
        @room = Room.new
    end

    def create
        @room = Room.new(room_params)
        if @room.save
            redirect_to room_path(@room.id)
        else
            render :new
        end
    end

    def show
        @room = Room.find(params[:id])
        @answer = Answer.create
        @answers = @room.answers.includes(:user)
    end

    private

    def room_params
        params.require(:room).permit(:target).merge(user_id: current_user.id)
    end

    def room_all
        @rooms = Room.all
    end

end

app/helpers/answer_helper.rb
module AnswerHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/answers/index.html.erb
<div class="main-center">中
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>Yourself</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= javascript_pack_tag 'application'%>
    
    

  </head>

  <body>
    <%= render "shared/header" %>
    <%= yield %>
    <%= render "shared/footer" %>
    <script src="https://unpkg.com/axios/dist/axios.min.js"><script>
  </body>
</html>

app/views/rooms/index.html.erb
<div class="roombody">
    <%= render "shared/side_list" %>
    <div class="analysis">
        <div class="analysis-content">
            <%= link_to '自己分析を始める', new_room_path, class:"btn btn-success analysis-size" %>
        </div>
    </div>
    
    <div class="explan">
        <div class="text-center">
            機能説明
        </div>
        <div class="explan-text">
            <%= render "shared/contents" %>

        </div>
    </div>
</div>

app/views/rooms/new.html.erb
<div class="new-roombody">
    <%= render "shared/side_list" %>
    <div class="will">
        <%= form_with(model:@room, url: rooms_path, method: :post, local: true) do |f| %>
                <p class="sengen">目標を宣言してください</p>
                <div class="new-form form-group">
                    <%= f.text_area :target ,id: "target", rows: "1", class: "form-control" %>
                    </div>
                    <div class="new-form form-group">
                    <%= f.submit '決定', id: "target-submit", class: "form-control btn btn-success" %>
                </div>
        <% end %>
    </div>
</div>

app/views/rooms/show.html.erb
<div class="UI_Build_Assistant homebody">

    <%= render "shared/side_list" %>
    <main class="text-center">
        <div class="target-name shadow box17">
            <b><%= @room.target %></b>
        </div>
        <p class="text-center ">何故そうありたいですか？</p>
    </main>

    <div class="main-left">
        <% @answers.each do |an| %>
            <% if an.point == 1 %>
                <div class="show-ans border border-success shadow p-1 bg-white rounded">
                    <%= an.ans %>
                </div>
                <div class="center-line text-center">|
                </div>
                <% next %>
            <% else %>
                <% next %>
            <% end %>
        <% end %>
        <%= form_with model: [@room, @answer] do |f| %>
            <div class="d">
                <%= f.text_area :ans, placeholder: "コメントする", rows: "1", class:"form-control" %>
            </div>
            <span class="separate"><%= f.select :point, [["左です！","1"]] %></span>
            <div class="send-btn">
                <%= f.submit "送信する", class:"btn btn-success" %>
            </div>
        <% end %>
    </div>

    <div class="main-center">
                <% @answers.each do |an| %>
                    <% if an.point == 2 %>
                        <div class="show-ans border border-success shadow p-1 bg-white rounded">
                            <%= an.ans %>
                        </div>
                        <div class="center-line">
                            <div class="center-line text-center">|
                            </div>
                        </div>
                        <% next %>
                    <% else %>
                        <% next %>
                    <% end %>
                <% end %>
        <%= form_with model: [@room, @answer] do |f| %>
            <div class="d">
                <%= f.text_area :ans, placeholder: "コメントする", rows: "1", class:"form-control" %>
            </div>
            <span class="separate"><%= f.select :point, [["中です！","2"]] %></span>
            <div class="send-btn">
                <%= f.submit "送信する", class:"btn btn-success" %>
            </div>
        <% end %>
    </div>

    <div class="main-right">
        <% @answers.each do |an| %>
            <% if an.point == 3 %>
                <div class="show-ans border border-success shadow p-1 bg-white rounded">
                    <%= an.ans %>
                </div>
                <div class="center-line text-center">|
                </div>
                <% next %>
            <% else %>
                <% next %>
            <% end %>
        <% end %>
        <%= form_with model: [@room, @answer] do |f| %>
            <div class="d">
                <%= f.text_area :ans, placeholder: "コメントする", rows: "1", class:"form-control" %>
            </div>
            <span class="separate"><%= f.select :point, [["右です！","3"]] %></span>
            <div class="send-btn">
                <%= f.submit "送信する", class:"btn btn-success" %>
            </div>
        <% end %>
    </div>

    <aside>right</aside>
    
</div>

app/views/shared/_contents.html.erb
<div class="text-templet border border-success">
<br>
<h2>どんなアプリ？</h2>
<h5>
    ・目標を達成したいと思ったきっかけ、理由、達成後の目的を深堀りしていきます！<br>
    ・きっかけ、理由、達成後の目的に対して「何故？」と繰り返し問いかけることで目標の真意に辿り着き、目標に対する軸が定まります！<br>

</h5>
<br>
<h2>利用方法</h2>
<h5>
<p>1.ページ上部にある"自己分析を始める"ボタンをクリック<br>
2.目標を入力して自己分析開始！<br>
3.宣言した目標を「何故？」達成したいのか答えよう！<br>
4.答えに対してさらに「何故？」なのか問い詰めていく！<br>
5.解答を繰り返し、理由を引き出し切ったところで自己分析終了！<br>
6.最後に自身の目標と解答を見直し、目標に対する想いの真意を見つめ直そう！</p>
</h5>


</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
これより下はfooterです。

app/views/shared/_header.html.erb
<header>
  <div class="header-group">
    <%= link_to image_tag('search-picture.png', class:"app-log", size: "140x70"), root_path %>
    <div class="container">
      自己分析
    </div>
    <div class='header-nav'>
      <div class="header-margin">
        <ul>
          <% if user_signed_in? %>
          <div class="header-menu">
            <li><%= link_to current_user.nickname, edit_user_registration_path, class: "user-nickname btn btn-link", :style=>"color:black;" %></li>
            <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout btn btn-link"  %></li>
          </div>
          <% else %>
            <li><%= link_to 'ログイン', user_session_path, class: "login btn btn-link" %></li>
            <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up btn btn-link" %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/shared/_side_list.html.erb
<nav>
    <p class="menulist">MenuList</p>
    <div>
        <div>
            <select class="btn btn-success side-list">リスト
                <option value="">過去の分析一覧</option>
                <% @rooms.each do |room| %>
                    <option><%= link_to "#{room.target}", room_path(room.id) %></option>
                    <p></p>
                <% end %>
            </select>
        </div>
    </div>    
</nav>